[server]
address = "127.0.0.1"
port = 8502
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#315FCE"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#EDF2FA"
textColor = "#18263E"
font = "sans serif"
